// Copyright (c) 2018-2020 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_shader_subgroup_partitioned.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-11-12
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/nv/GL_NV_shader_subgroup_partitioned.txt[`GL_NV_shader_subgroup_partitioned`]
*Contributors*::
  - Jeff Bolz, NVIDIA

=== Description

This extension enables support for a new class of
<<shaders-group-operations, group operations>> on <<shaders-scope-subgroup,
subgroups>> via the
{GLSLregistry}/nv/GL_NV_shader_subgroup_partitioned.txt[`GL_NV_shader_subgroup_partitioned`]
GLSL extension and
{spirv}/NV/SPV_NV_shader_subgroup_partitioned.html[`SPV_NV_shader_subgroup_partitioned`]
SPIR-V extension.
Support for these new operations is advertised via the
ename:VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV bit.

This extension requires Vulkan 1.1, for general subgroup support.

=== Promotion to `VK_EXT_shader_subgroup_partitioned`

All functionality in this extension is included in
`apiext:VK_EXT_shader_subgroup_partitioned`, with the suffix changed to EXT.
The original type, enum, and command names are still available as aliases of
the core functionality.

include::{generated}/interfaces/VK_NV_shader_subgroup_partitioned.adoc[]

=== Version History

  * Revision 1, 2018-03-17 (Jeff Bolz)
  ** Internal revisions
